baseurl = "http://rubentan.com/"
title = "Ruben Tan - a technologist's viewpoint"
languageCode = "en-us"
publishdir = "../"
theme = "rubentan"

[taxonomies]
tag = "tags"
type = "types"
series = "series"